"""Tests for landingpage/scripts/generate_decay_nuclides.py."""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "landingpage" / "scripts" / "generate_decay_nuclides.py"


@pytest.fixture(scope="module")
def gen():
    spec = importlib.util.spec_from_file_location("generate_decay_nuclides", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# --- time_unit -------------------------------------------------------------


def test_time_unit_sub_day_uses_hours(gen):
    unit, per_unit, display = gen.time_unit(0.250281)
    assert unit == "hours"
    assert per_unit == pytest.approx(1 / 24)
    assert display == "6.007 hours"


def test_time_unit_boundary_exactly_one_day_uses_days(gen):
    unit, per_unit, display = gen.time_unit(1.0)
    assert unit == "days"
    assert per_unit == 1.0
    assert display == "1 days"


def test_time_unit_just_under_one_day_uses_hours(gen):
    unit, _, _ = gen.time_unit(0.9999)
    assert unit == "hours"


def test_time_unit_icrp107_iodine131(gen):
    days = 692988.48 / 86400.0
    unit, _, display = gen.time_unit(days)
    assert unit == "days"
    assert display == "8.0207 days"


def test_time_unit_half_year_boundary(gen):
    year_half = 365.2422 / 2
    assert gen.time_unit(year_half - 0.1)[0] == "days"
    assert gen.time_unit(year_half + 0.1)[0] == "years"


def test_time_unit_years_display_and_days_per_unit(gen):
    unit, per_unit, display = gen.time_unit(1925.23)
    assert unit == "years"
    assert per_unit == 365.2422
    assert display == "5.271 years"


def test_time_unit_geologic_years_avoids_e_plus_notation(gen):
    unit, _, display = gen.time_unit(4.468e9 * 365.2422)
    assert unit == "years"
    assert "e+0" not in display
    assert "years" in display


# --- element_name ----------------------------------------------------------


@pytest.mark.parametrize(
    ("symbol", "expected"),
    [
        ("I", "Iodine"),
        ("Co", "Cobalt"),
        ("Cs", "Cesium"),
        ("Tc", "Technetium"),
        ("U", "Uranium"),
        ("Pb", "Lead"),
        ("Ag", "Silver"),
    ],
)
def test_element_name_known_symbols(gen, symbol, expected):
    assert gen.element_name(symbol) == expected


def test_element_name_unknown_symbol_passes_through(gen):
    assert gen.element_name("Xx") == "Xx"


def test_symbol_names_covers_all_118_elements(gen):
    assert len(gen.SYMBOL_NAMES) == 118


# --- build_rows ------------------------------------------------------------


@pytest.fixture(scope="module")
def rows(gen):
    return gen.build_rows()


def test_build_rows_cardinality_between_demo_and_full_catalog(gen, rows):
    assert 1200 <= len(rows) <= 1400


def test_build_rows_sorted_and_unique(rows):
    ids = [row.id for row in rows]
    assert ids == sorted(ids)
    assert len(set(ids)) == len(ids)


def test_build_rows_excludes_stable_endpoints(rows):
    ids = {row.id for row in rows}
    assert "Ag-107" not in ids  # stable in ICRP-107, half_life_s == inf
    assert "I-131" in ids


def test_build_rows_icrp107_iodine131_days(rows):
    i131 = next(row for row in rows if row.id == "I-131")
    assert i131.days == pytest.approx(692988.48 / 86400.0)
    assert i131.element == "Iodine"
    assert i131.time_unit == "days"
    assert i131.days_per_unit == 1.0


def test_build_rows_all_ids_parse_and_symbols_resolve(gen, rows):
    for row in rows:
        match = gen._ID_RE.match(row.id)
        assert match is not None, row.id
        assert match.group(1) in gen.SYMBOL_NAMES, row.id
        assert row.element == gen.SYMBOL_NAMES[match.group(1)]


def test_build_rows_all_values_finite_and_positive(rows):
    for row in rows:
        assert row.days > 0
        assert row.days_per_unit > 0
        assert row.display and row.element


def test_build_rows_technetium99m_is_hours(rows):
    tc99m = next(row for row in rows if row.id == "Tc-99m")
    assert tc99m.time_unit == "hours"
    assert tc99m.days < 1


def test_build_rows_uranium238_is_years(rows):
    u238 = next(row for row in rows if row.id == "U-238")
    assert u238.time_unit == "years"
    assert u238.days > 365.2422


# --- render / output_path / main ------------------------------------------


def test_render_header_and_import(gen, rows):
    source = gen.render(rows[:5])
    assert source.startswith("// GENERATED by landingpage/scripts/generate_decay_nuclides.py")
    assert 'import type { DemoNuclide } from "./nuclides";' in source
    assert source.endswith("];\n")


def test_render_contains_every_row_exactly_once(gen, rows):
    source = gen.render(rows)
    assert source.count("    id: ") == len(rows)
    for row in rows:
        assert f'id: "{row.id}"' in source


def test_render_never_emits_python_float_sentinels(gen, rows):
    source = gen.render(rows)
    for sentinel in ("inf", "None", "nan"):
        assert not re.search(rf"\b{sentinel}\b", source)


def test_fmt_float_normalizes_python_exponents(gen):
    assert gen.fmt_float(5.324074074074074e-05) == "5.324074074074074e-5"
    assert gen.fmt_float(1.1574074074074074e-09) == "1.1574074074074074e-9"
    assert gen.fmt_float(2.812425e18) == "2.812425e18"
    assert gen.fmt_float(1.0) == "1.0"
    assert gen.fmt_float(365.2422) == "365.2422"
    assert gen.fmt_float(0.041666666666666664) == "0.041666666666666664"


def test_render_uses_js_exponent_style_everywhere(gen, rows):
    """Prettier rewrites e-05/e+18 to e-5/e18; emit the prettier-stable form.

    Display strings are exempt: prettier never touches string contents.
    """
    source = gen.render(rows)
    for line in source.splitlines():
        stripped = line.strip()
        if stripped.startswith(("halfLifeDays:", "daysPerUnit:")):
            assert "e+" not in line, line
            assert not re.search(r"e-0\d", line), line


def test_render_is_deterministic(gen, rows):
    assert gen.render(rows) == gen.render(rows)


def test_output_path_points_at_expected_file(gen):
    path = gen.output_path()
    assert path.name == "decayNuclides.ts"
    assert path.parent == ROOT / "landingpage" / "src" / "data"


def test_committed_file_is_fresh(gen, rows):
    """The checked-in decayNuclides.ts must match a fresh render."""
    on_disk = gen.output_path().read_text(encoding="utf-8")
    assert on_disk == gen.render(rows)
